timberio/timber-ruby

README.md
lib/timber.rb
lib/timber/log_devices/http.rb
lib/timber/log_devices/http/triggered_buffer.rb
lib/timber/logger.rb
spec/timber/log_devices/http/triggered_buffer_spec.rb
spec/timber/log_devices/http_spec.rb
spec/timber/logger_spec.rb
timberio.gemspec

Implements HTTP transport. The buffer strategy is triggered, where payloads are delivered if they attempt to exceed the 5mb (default) limit. The overall buffer limit is 50mb (default) and buffer overflows are handled with the `:buffer_overflow_handler` option, where the user can pass a `Proc`  that handles persisting the data.

HTTP Transport

---

README.md
lib/timber/context.rb
lib/timber/contexts.rb
lib/timber/contexts/custom.rb
lib/timber/contexts/http.rb
lib/timber/contexts/organization.rb
lib/timber/contexts/tags.rb
lib/timber/contexts/user.rb
lib/timber/current_context.rb
lib/timber/log_devices/http.rb
lib/timber/probes.rb
lib/timber/probes/active_support_tagged_logging.rb
lib/timber/probes/rack_http_context.rb
lib/timberio.rb
spec/timber/logger_spec.rb
spec/timber/probes/rack_http_context_spec.rb
timber.gemspec

No idea why rails would decide to pollute the logger with all of this, but here we go! This also requires us to add the `context.tags` keyspace which is silly when we have custom contexts. Hence the warnings in the docs.

Support ActiveSupport::TaggedLogging

---

lib/timber/context.rb
lib/timber/contexts.rb
lib/timber/contexts/system.rb
lib/timber/event.rb
lib/timber/log_entry.rb
spec/timber/log_devices/http_spec.rb
spec/timber/log_entry_spec.rb
spec/timber/logger_spec.rb
spec/timber/probes/action_controller_log_subscriber_spec.rb
spec/timber/probes/action_view_log_subscriber_spec.rb
spec/timber/probes/rails_rack_logger_spec.rb
spec/timber/rack_middlewares/http_context_spec.rb

As pointed out by @DavidAntaramian via http://man7.org/linux/man-pages/man2/getpid.2.html:
Since glibc version 2.3.4, the glibc wrapper function for getpid()
caches PIDs, so as to avoid additional system calls when a process
calls getpid() repeatedly.  Normally this caching is invisible, but
its correct operation relies on support in the wrapper functions for
fork(2), vfork(2), and clone(2): if an application bypasses the glibc
wrappers for these system calls by using syscall(2), then a call to
getpid() in the child will return the wrong value (to be precise: it
will return the PID of the parent process).  See also clone(2) for
discussion of a case where getpid() may return the wrong value even
when invoking clone(2) via the glibc wrapper function.
This should not affect performance.

Implement System context

---

lib/timber/log_entry.rb
spec/timber/log_devices/http_spec.rb
spec/timber/log_entry_spec.rb

Adds `$schema` to the payload so that we can support versions properly.

Specify the log event schema

---

lib/timber/integrations/rack/user_context.rb

This PR fixes an authentication issue when both warden and omniauth are installed. `env['warden']` always returns a proxy object, even if the user is not authed, so the previous if statement would always return true. `env['warden'].user` will determine if the user is logged in or not.

Hotfix for user auth when both omniauth and warden are installed

---

spec/timber/util/http_event_spec.rb

The fix for this was pushed in a previous commit, but I wanted to get a test in place and officially close the issue:
Closes https://github.com/timberio/timber-ruby/issues/77

Add spec for nil values when normalizing headers

---

lib/timber/frameworks/rails.rb

This ensures Timber comes after all authentication middleware, ensuring that we capture user context.

Make sure Timber is the absolute last middleware inserted

---

lib/timber/log_entry.rb
spec/timber/logger_spec.rb

The default ruby `::Logger` calls `inspect` on any object logged, this does the same.

Support logging non-string objects

---

lib/timber/events/controller_call.rb
lib/timber/events/exception.rb
lib/timber/events/http_client_request.rb
lib/timber/events/http_client_response.rb
lib/timber/events/http_server_request.rb
lib/timber/events/http_server_response.rb
lib/timber/events/sql_query.rb
lib/timber/events/template_render.rb
lib/timber/log_entry.rb
lib/timber/version.rb
spec/timber/integrations/action_controller/log_subscriber_spec.rb
spec/timber/integrations/action_dispatch/debug_exceptions_spec.rb
spec/timber/integrations/action_view/log_subscriber_spec.rb
spec/timber/integrations/active_record/log_subscriber_spec.rb
spec/timber/logger_spec.rb

This PR removes the sub-level `event` namespace in the resulting event structure. This simplifies the JSON and decouples it from Timber.

Remove event namespace

---

lib/timber/config.rb
lib/timber/frameworks/rails.rb
spec/support/rails.rb

This removes setting the Rails logger explicitly in the `Railtie`. This code was legacy when we automatically installed timber and / or recommended an initializer. Because the Timber logger is now being set in the appropriate environment files we don't need to do any of this.

Allow Rails to set the logger

---

.travis.yml
lib/timber/config.rb
lib/timber/frameworks/rails.rb
lib/timber/integrations/active_record/log_subscriber/timber_log_subscriber.rb
lib/timber/log_devices/http.rb
lib/timber/logger/metadata_methods.rb
spec/support/timber.rb
spec/timber/log_devices/http_spec.rb

This PR handles request errors by closing the current HTTP connection and allowing the outlet loop to build a new connection. This is needed for errors like "Conn close because of keep_alive_timeout".

Handle request errors by starting a new connection

---

.travis.yml
gemfiles/rails-5.1.gemfile
lib/timber/config.rb
lib/timber/contexts.rb
lib/timber/contexts/session.rb
lib/timber/contexts/user.rb
lib/timber/log_entry.rb
lib/timber/overrides.rb
lib/timber/overrides/active_support_tagged_logging.rb
spec/rails/tagged_logging_spec.rb
spec/timber/logger_spec.rb

This patch is specifically for Rails 3. The legacy approach to wrapping the logger in ActiveSupport::TaggedLogging is rather poor, hence the reason it was changed entirely for Rails 4 and 5. The problem is that ActiveSupport::TaggedLogging is a wrapping class that entirely redefines the public API for the logger. As a result, any deviations from this API in the logger are not exposed (such as accepting event data as a second argument). This is assuming, so we're fixing it here.

For Rails 3, fix ActiveSupport::TaggedLogging to not redefine the public Logger API

---

README.md
lib/timber/logger.rb
spec/timber/logger_spec.rb

Rails accepts symbols when setting the Rails configuration:
```
config.log_level = :debug
```
This is a little misleading because they then extract the constant [here](ActiveSupport::Logger.const_get(config.log_level.to_s.upcase). Instead of doing the same, we're going to support symbols for `Timber::Logger#level=` since this feels more user friendly, especially since Rails introduces the concept of symboled levels.
Closes https://github.com/timberio/timber-ruby/issues/98

Accept symbols for Logger#level=

---

lib/timber/events/exception.rb
spec/timber/events/exception_spec.rb

According to the [ruby docs](https://ruby-doc.org/core-2.2.0/Exception.html#method-i-backtrace):
> The backtrace is an array of strings, each containing either “filename:lineNo: in `method”‘ or “filename:lineNo.”
This accounts for the 2 formats mentioned as well as being defensive for unknown formats.

Be more defensive with exception line parsing

---

lib/timber/config.rb
lib/timber/events/controller_call.rb
lib/timber/events/exception.rb
lib/timber/events/sql_query.rb
lib/timber/log_entry.rb
lib/timber/util/http_event.rb

This ensures attributes of the log even adhere to the byte limits specified in the JSON schema.

Enforce JSON schema byte limits

---

README.md
lib/timber/config/integrations/rack.rb
lib/timber/events.rb
lib/timber/events/error.rb
lib/timber/integrations/action_dispatch.rb
lib/timber/integrations/rack.rb
lib/timber/integrations/rack/error_event.rb
lib/timber/log_entry.rb
spec/timber/events/error_spec.rb
spec/timber/integrations/action_dispatch/debug_exceptions_spec.rb

This updates the library to use [`2.4.0` of our log event JSON schema](https://github.com/timberio/log-event-json-schema/releases/tag/v2.4.0) renaming `ExceptionEvent` to `ErrorEvent`.

Rename Exception to Error

---

lib/timber/contexts/runtime.rb
lib/timber/current_context.rb

This adds the `context.runtime.vm_pid` field making it possible to segment logs by the current thread id.

Use the current thread object_id as the vm_pid

---

lib/timber/contexts/system.rb
lib/timber/events/http_request.rb
lib/timber/log_entry.rb
spec/timber/contexts/system_spec.rb

Adjusts the `HTTPRequest` event requirements to make `host` and `scheme` optional. This follows the [HTTP 1.0 specification](https://www.w3.org/Protocols/HTTP/1.0/spec.html).

Adjust http request requirements

---

lib/timber/log_devices.rb
lib/timber/log_devices/multi.rb
lib/timber/logger.rb
spec/timber/logger_spec.rb

This PR allows passing multiple IO devices to `Timber::Logger#new`.

Allow logging to multiple devices

---

lib/timber/events/exception.rb

This adds `Timber::Events::Exception` as a deprecated class. This class has been renamed to `Timber::Events::Error` for simplicity across platforms. This allows all error and exception events to be represented as a single event. For example, Heroku platform errors are mapped as errors, as well as internal Ruby exceptions.

Add deprecated Exception event class

---

lib/timber/cli/api/application.rb
lib/timber/cli/io/messages.rb
spec/timber/cli/installers/config_file_spec.rb
spec/timber/cli/installers/other_spec.rb
spec/timber/cli/installers/rails_spec.rb
spec/timber/cli/installers/root_spec.rb

Removing this field since it no longer exists in the API.

Remove framework_type in installer

---

README.md
lib/timber.rb
lib/timber/logger.rb

This adds a simple top-level API that makes it easier to use core feature of Timber.

Add a simple top-level API

---

.travis.yml
lib/timber/cli/config_file.rb
lib/timber/cli/file_helper.rb
lib/timber/cli/installers/config_file.rb
lib/timber/cli/installers/rails.rb
lib/timber/cli/installers/root.rb
lib/timber/cli/io.rb
lib/timber/cli/io/messages.rb
spec/timber/cli/installers/config_file_spec.rb
spec/timber/cli/installers/rails_spec.rb
spec/timber/cli/installers/root_spec.rb

This improves the installer by:
1. Removing the prompt asking them if the app details are correct.
2. Assume they want to silence template rendering in production. This makes for a better overall timber experience. These logs are designed for development.
3. Assume they want to enable the logrageify option if they already have lograge installed.
4. Remove the git commands. This is too assuming and can be destructive, especially if git hooks are installed.
5. Moves the "commit and deploy" message to be last since this is what you immediately read when the installer finishes.
6. Remove the Heroku / platform installation step since this is handled inside the timber app.

Improve installer

---

lib/timber/log_entry.rb

On Windows this method is not present without a require of the `time` library.

Require time to ensure the iso8601 method is available

---

lib/timber/current_context.rb
spec/timber/current_context_spec.rb

The `runtime` context was erroneously using the `Contexts::System` for initialization. This was overriding the `system` context with a blank map. This change uses the correct class and adds tests for capturing these contexts properly.

Resolve capturing system and runtime context

---

lib/timber/contexts/custom.rb
lib/timber/contexts/organization.rb
lib/timber/contexts/runtime.rb
lib/timber/contexts/session.rb
lib/timber/contexts/system.rb
lib/timber/contexts/user.rb
spec/timber/contexts/system_spec.rb

This coerces the `context.runtime.vm_pid` field into a string, which is defined by our log event JSON schema. Currently this is being set as an integer. We cannot assume this is an integer since other languages and systems use strings.

Coerce vm_pid into a String

---

CHANGELOG.md
README.md
lib/timber/integrations/rack/user_context.rb

Omniauth is a blackbox, it does not implement sessions or persist authentication. This is left up to the application to implement and is usually achieved by libraries like Devise. In some cases Omniauth integrations are not idempotent (like they should be), and accessing the user hash results in unexpected behaviour. Because capturing Omniauth user context is lower value, and the risk of causing unintended behaviour, we've decided to remove this integration.
Closes https://github.com/timberio/timber-ruby/issues/152

Remove Omniauth user context capturing

---

CHANGELOG.md
lib/timber/cli/installer.rb
lib/timber/cli/installers/other.rb

Original versions of the installer checked for Heroku directly. This updates the installer to be aware of our multiple platforms, choosing the appropriate delivery method.

Update installer method to be platform aware

---

CHANGELOG.md
lib/timber/logger.rb
spec/timber/logger_spec.rb

Allows logging to multiple loggers. Ex:
```ruby
http_device = Timber::LogDevices::HTTP.new("my-timber-api-key")
file_logger = ::Logger.new("path/to/file.log")
logger = Timber::Logger.new(http_device, file_logger)
```
Closes https://github.com/timberio/timber-ruby/issues/159

Allowing logging to multiple loggers

---

CHANGELOG.md
lib/timber/cli/api.rb

Older versions of OpenSSL will attempt to using SSLv3 which is not supported, this change forcibly falls back to SSLv23 is this is the case.
Closes https://github.com/timberio/timber-ruby/issues/161

Forcibly fallback to SSLv23 if SSLv3 fails

---

.travis.yml
CHANGELOG.md
lib/timber/log_entry.rb
lib/timber/util/hash.rb
spec/spec_helper.rb
spec/timber/log_entry_spec.rb

Fixes JSON encoding errors while attempting to encode binary data.
Closes https://github.com/timberio/timber-ruby/issues/163

Drop ASCII-8BIT (binary) strings before encoding log data to JSON

---

lib/timber/config.rb

`debug_to_file!()` didn't work as the docs said it did.
- `debug_to_file!` referenced a variable `path` that should have been `file_path`
- no need to check if the directory exists as `mkdir_p` only creates the path if it doesn't already exist.
- File.open(..., "ab") opens the file in binary mode
- removed `.sync = config.autoflush_log` as `autoflush_log` doesn't exist anywhere and the Logger.initializer already sets `sync` to `true`

get debug_to_file! to work

---

.travis.yml
CHANGELOG.md
lib/timber/cli/api.rb
lib/timber/events/controller_call.rb

Raises the `ControllerCall#params_json` limit to `32768` bytes to match this change: https://github.com/timberio/log-event-json-schema/pull/34

Raise params_json limit to match the new JSON schema limit of 32_768

---

CHANGELOG.md
lib/timber/contexts/http.rb
lib/timber/integrations/rack/http_context.rb
lib/timber/log_entry.rb
spec/timber/integrations/rack/http_context_spec.rb

This updates the log event JSON schema to `v3.2.0` which supports the new `host` attribute in the `http` context. This is useful for apps that are spread across multiple domains, including sub-domains. Timber will be adding this field as a facet if it contains a cardinality > 1.

Add host to the HTTP context

---

CHANGELOG.md
lib/timber/cli/installers/root.rb
lib/timber/cli/io/messages.rb
spec/timber/cli/installers/root_spec.rb

This removes the free data social promotions during the installation process. Integrating this with our billing system and making it available in the interface has proven to be much more difficult than anticipated. Currently, all customers are receiving this promotion, but it is not indicated on the interface. Any customer that participated will continue to receive this promotion and it will be made available in the billing interface as soon as we have the capability to do so.

Remove social promotions 😢

---

CHANGELOG.md
lib/timber/overrides.rb
lib/timber/overrides/active_support_3_tagged_logging.rb
lib/timber/overrides/active_support_buffered_logger.rb
spec/rails/tagged_logging_spec.rb

This adds a #formatter and #formatter= method to the legacy ActiveSupport::BufferedLogger class. This bug was never resolved due to it being phased out past Rails >= 4.

Add #formatter accessor methods to ActiveSupport::BufferedLogger

---

lib/timber/cli/api.rb

Closes https://github.com/timberio/timber-ruby/issues/161

Use TLSv1_2 as a fallback for the installer if an SSL error is encountered

---

CHANGELOG.md
lib/timber/events/http_request.rb
lib/timber/events/http_response.rb
lib/timber/integrations/rack/http_events.rb
spec/support/rails.rb
spec/timber/integrations/rack/http_events_spec.rb

Adds the `content_length` field to both `http_request` and `http_response` events.
Closes https://github.com/timberio/timber-ruby/issues/170

Add content_length to both http_request and http_response events

---

lib/timber/integrations/rack/http_events.rb

`Rack::ContentLength` does not exist for all versions of `Rack`.

Fix Rack::ContentLength missing constant error

---

CHANGELOG.md
lib/timber/events/error.rb
lib/timber/integrations/rack/error_event.rb
lib/timber/util/attribute_normalizer.rb
lib/timber/version.rb
spec/timber/integrations/rack/error_event_spec.rb

This PR updates how we detect versions of the `::ActionDispatch::ExceptionWrapper` class. Previously we were determining this via:
```ruby
Gem.loaded_specs["rails"].version >= Gem::Version.new('5.0.0')
```
This has proved to be unreliable across environments. Instead, we're checking the actual class behaviour directly via `.instance_methods`. This resolves https://github.com/timberio/timber-ruby/issues/183 since this was causing Timber to pass the entire Rack env hash to this class.
Closes https://github.com/timberio/timber-ruby/issues/183

Improve ExceptionWrapper compatibility detection

---

CHANGELOG.md
lib/timber/current_context.rb
lib/timber/log_devices/http.rb
spec/timber/current_context_spec.rb

This resolves a bug where the reference to the current custom context map was being passed to the backend log device while later being modified, thus making the log line invalid before being transmitted.

Fix blank custom context errors

---

lib/timber/current_context.rb

Suggesting this because I just wasted a bunch of time trying to add a custom context that was incorrectly formatted (tried with all the keys at the root and with multiple root keys).
Ideally there would be an informative error but I don't know if it's reasonable to have `Timber::Contexts.build` raise an error when the passed in `obj` either has two root keys or has one root key but the value is not a hash. Right now those fail with errors like:
> Timber::CurrentContext.with({other: 42}, &block)
NoMethodError:
undefined method `each' for 42:Fixnum
> Timber::CurrentContext.with({first_key: 1, second_key: 2}, &block)
NoMethodError:
undefined method `keyspace' for nil:NilClass
If it makes sense I could add code to detect those two cases and raise an informative `ArgumentError` in …

Add more info to the docs about adding custom contexts

---

CHANGELOG.md
lib/timber/util/hash.rb
spec/timber/util/hash_spec.rb

I noticed that whenever the parameters of my request would be something
along the lines of:
```
{
user_id: 124,
post: { title: "My Post", body: "This is really awesome" }
}
```
I would end only seeing logs with:
```
{
user_id: 124
}
```
And the entire post was left somewhere in the dark. It turns out that
the jsonify method was not retaining nested hashes.

Don't cut out nested hashes from parameters

---

lib/timber/current_context.rb
spec/timber/current_context_spec.rb

This re-adds the `CurrentContext.with` method that was accidentally removed due to compatibility issues with the new API. This PR fixes that.
Closes https://github.com/timberio/timber-ruby/issues/204

Re-add CurrentContext.with
